/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.plugin.test;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class MyPlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {

    }
}
