/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lockfiles.old.config.issue;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
