/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idea.module.deprecation.issue;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
