{
  "formatVersion": "1.1",
  "component": {
    "group": "netflix",
    "module": "platform",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6-rc-4",
      "buildId": "5q4lz5xy7bhv3ey2syzzs733gi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [],
      "dependencyConstraints": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "19.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "dependencyConstraints": [
              {
                "group": "com.google.guava",
                "module": "guava",
                "version": {
                  "requires": "19.0"
                }
              }
            ]
    }
  ]
}
