/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ivy.resolve.from.sbt.published;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
