/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compile.multiple.versions.utilities;

public class StringUtils {
    public static String test() {
        return "ok";
    }
}
