{
  "formatVersion": "0.4",
  "component": {
    "group": "tree",
    "module": "blue-palo-verde",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.1-20181127213941+0000",
      "buildId": "aaaaabbbbbcccccdddddeeeeef"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "tree",
          "module": "acacia",
          "version": {
            "prefers": "1.5"
          }
        },
        {
          "group": "tree",
          "module": "acacia",
          "version": {
            "requires": "[1.2, 2.0)"
          }
        }
      ],
      "files": [
        {
          "name": "blue-palo-verde-1.0.jar",
          "url": "blue-palo-verde-1.0.jar",
          "size": 261,
          "sha1": "0123456789012345678901234567890123456789",
          "md5": "01234567890123456789012345678901"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tree",
          "module": "acacia",
          "version": {
            "prefers": "1.5"
          }
        },
        {
          "group": "tree",
          "module": "acacia",
          "version": {
            "requires": "[1.2, 2.0)"
          }
        }
      ],
      "files": [
        {
          "name": "blue-palo-verde-1.0.jar",
          "url": "blue-palo-verde-1.0.jar",
          "size": 261,
          "sha1": "0123456789012345678901234567890123456789",
          "md5": "01234567890123456789012345678901"
        }
      ]
    }
  ]
}
