{
  "formatVersion": "1.1",
  "component": {
    "group": "gid",
    "module": "baf",
    "version": "3.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1-20191006220021+0000",
      "buildId": "2pylsxpe3vemvmed26wwzvkaoe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "baf-3.0-rc.1.jar",
          "url": "baf-3.0-rc.1.jar",
          "size": 261,
          "sha1": "f6755d2ac3eba83ae4c0fa363e7aff938a477805",
          "md5": "fd770fb2acc656754897796785961f5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "baf-3.0-rc.1.jar",
          "url": "baf-3.0-rc.1.jar",
          "size": 261,
          "sha1": "f6755d2ac3eba83ae4c0fa363e7aff938a477805",
          "md5": "fd770fb2acc656754897796785961f5f"
        }
      ]
    }
  ]
}
