/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compile.multiple.versions.app;

import compile.multiple.versions.utilities.StringUtils;

public class App {
    public static void main(String[] args) {

        System.out.println(StringUtils.test());
    }
}
